# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"J\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x18\n\x10publication_date\x18\x04 \x01(\t\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x0e\n\x0c\x45mptyMessage\"-\n\x10GetBooksResponse\x12\x19\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\n.book.Book2v\n\x0b\x42ookService\x12/\n\x0bGetBookById\x12\x14.book.GetBookRequest\x1a\n.book.Book\x12\x36\n\x08GetBooks\x12\x12.book.EmptyMessage\x1a\x16.book.GetBooksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=20
  _globals['_BOOK']._serialized_end=94
  _globals['_GETBOOKREQUEST']._serialized_start=96
  _globals['_GETBOOKREQUEST']._serialized_end=124
  _globals['_EMPTYMESSAGE']._serialized_start=126
  _globals['_EMPTYMESSAGE']._serialized_end=140
  _globals['_GETBOOKSRESPONSE']._serialized_start=142
  _globals['_GETBOOKSRESPONSE']._serialized_end=187
  _globals['_BOOKSERVICE']._serialized_start=189
  _globals['_BOOKSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
